
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const SORT_COMMENT = 'SORT_COMMENT';
export const CHANGE_SORT_KEY = 'CHANGE_SORT_KEY';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const IS_SHOW_COMMENT_DIALOG = 'IS_SHOW_COMMENT_DIALOG';
export const ADD_COMMENT = 'ADD_COMMENT';
export const CHANGE_CURRENT_COMMENT = 'CHANGE_CURRENT_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';


export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const VOTE_POST = 'VOTE_POST';
export const DELETE_POST = 'DELETE_POST';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SORT_POST = 'SORT_POST'; 
export const IS_SHOW_POST_DIALOG = 'IS_SHOW_POST_DIALOG';
export const CHANGE_CURRENT_POST = 'CHANGE_CURRENT_POST';
